### ISSUE TITLE
issues when using in a pure node environment

### ISSUE THREAD

**Issue by rdy** [charleshansen/jasmine_dom_matchers#1]
There are a couple of issues I found when trying to use this in a pure node environment with a fake DOM.

Firstly it would be great if we could remove global references to HTMLElement and SVGSVGElement. Instead I believe we could use property checks to verify that an element looks DOMish.

The second issue I found was that the window object isn't quite available at require time, so in order to make this work with jsdom you need to add the matchers in a beforeEach that happens after the window has been installed. In the current scheme the functions are all added at once. It would be great if we could move the matchers themselves into a separate file so they could be required in a special beforeEach instead of the default behavior which is to just put them in a beforeEach.

If you are cool with these changes I'll send a pull request.

Here's an example of what I had to change:
https://gist.github.com/rdy/847d0641c478be26bfa2

**Comment by rdy** [comment]
Check out pull request #3

**Comment by charleshansen** [comment]
pull request merged 49ae103239ae12c8736f6cf728ff2431e43fff38
